# Numpy Tutorial

## Installation
To install numpy enter
```
pip3 install numpy
```
at a console. Maybe you need sudo. Thats it.

## Usage
To use numpy add the following to the python file

In [93]:
import numpy as np

In [94]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a[0,0]

1

In [96]:
a[0][0]

1

In [97]:
a[0,0] = 5
a

array([[5, 2, 3],
       [4, 5, 6]])

In [100]:
np.reshape(a, (1,-1))

array([[5, 2, 3, 4, 5, 6]])

In [101]:
np.reshape(a, (-1,1))

array([[5],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [102]:
a.T

array([[5, 4],
       [2, 5],
       [3, 6]])

In [135]:
a.sum()

25

In [103]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [104]:
np.ones((3,1))

array([[ 1.],
       [ 1.],
       [ 1.]])

In [105]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [106]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [107]:
b = np.random.random((3,4))
b

array([[ 0.43807723,  0.91890924,  0.02104357,  0.36688726],
       [ 0.94922869,  0.24838379,  0.55167817,  0.97249093],
       [ 0.63448056,  0.59870127,  0.97697463,  0.21543478]])

In [108]:
c = np.array((2.3,2), dtype=np.int64)
c

array([2, 2], dtype=int64)

In [110]:
c[0]

2

In [111]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [112]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [114]:
[b > 0.5]

[array([[False,  True, False, False],
        [ True, False,  True,  True],
        [ True,  True,  True, False]], dtype=bool)]

In [115]:
b[b > 0.5]

array([ 0.91890924,  0.94922869,  0.55167817,  0.97249093,  0.63448056,
        0.59870127,  0.97697463])

In [118]:
np.where(b > 0.5, b, 0)

array([[ 0.        ,  0.91890924,  0.        ,  0.        ],
       [ 0.94922869,  0.        ,  0.55167817,  0.97249093],
       [ 0.63448056,  0.59870127,  0.97697463,  0.        ]])

In [122]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
np.concatenate([arr1, arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [141]:
np.split(np.arange(10), [4,6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [142]:
np.repeat(a,2)

array([5, 5, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [145]:
arr = np.arange(10)
np.save('some_array', arr)
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.savez('array_archive.npz', a=arr)
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.exp(a)

array([[ 148.4131591 ,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349]])

In [150]:
np.sin(a)

array([[-0.95892427,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [151]:
np.sqrt(a)

array([[ 2.23606798,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [161]:
b = (np.arange(6)+1).reshape(2,3)
a == b

array([[False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [162]:
np.array_equal(a,b)

False

In [164]:
a.sort()
a

array([[2, 3, 5],
       [4, 5, 6]])

In [180]:
np.sum(a)

25

In [181]:
np.min(a)

2

In [182]:
np.max(a)

6

In [183]:
np.mean(a)

4.166666666666667

In [184]:
np.median(a)

4.5

In [185]:
np.corrcoef(a)

array([[ 1.        ,  0.98198051],
       [ 0.98198051,  1.        ]])

In [186]:
np.std(a)

1.3437096247164249

In [192]:
2 * a

array([[ 4,  6, 10],
       [ 8, 10, 12]])

In [188]:
a * a

array([[ 4,  9, 25],
       [16, 25, 36]])

In [190]:
a.dot(a.T)

array([[38, 53],
       [53, 77]])

In [191]:
a.T.dot(a)

array([[20, 26, 34],
       [26, 34, 45],
       [34, 45, 61]])